services:
  - type: web
    name: battlecats-web-editor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bcsfe_web.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
